### ISSUE TITLE
with scala 2.8.0 

### ISSUE THREAD

**Issue by m410** [stevej/scala-json#3]
Is there a way to get the library to work with the latest 2.8.0 release?

<pre>
[m410@m410 scala-json]% scala-2.8 -cp target/json-1.1.2.jar 
Welcome to Scala version 2.8.0.RC5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_20).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import com.twitter.json.Json
import com.twitter.json.Json

scala> val content = Json.build(Map("p0"->"v1","p1"->"v2"))
error: error while loading Json, Scala signature Json has wrong version
 expected: 5.0
 found: 4.1 in target/json-1.1.2.jar(com/twitter/json/Json.class)
</pre>

**Comment by robey** [comment]
it looks like scala 2.8 won't load class files generated by scala 2.7. :(

have you tried recompiling it against 2.8?

**Comment by m410** [comment]
Hi,
Yeah I tried changing project/build.properties and rebuilding but when I do that I get:

<pre>

[error] error while loading extensions, Scala signature extensions has wrong version
[error]  expected: 5.0
[error]  found: 4.1 in /Users/m410/Projects/Java/scala-json/lib_managed/compile/configgy-1.5.3.jar(net/lag/extensions.class)
[error] /Users/m410/Projects/Java/scala-json/src/main/scala/com/twitter/json/Json.scala:32: too many arguments for constructor Object: ()java.lang.Object
[error] class JsonException(reason: String) extends Exception(reason)
</pre>


I think the plugin used by sbt is also using the wrong version.  Removing the plugin doesn't work either.  Is the plugin source available somewhere?

thx
Mike

**Comment by robey** [comment]
yeah the plugin is on github: "standard-project".

not sure about the other error. it doesn't make any sense to me. :(
